name: Check updates

on:
  schedule:
    - cron: '0 */2 * * *'

env:
  BRANCH_PREFIX: automated
  NOTIFY_MATRIX: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔧 Install rust dependencies
        uses: ./.github/workflows/rust-install

      - name: Try to checkout exising PR branch
        id: checkout-pr
        run: |
          SIGN_ME_BRANCH=$(git branch -r --list "origin/$BRANCH_PREFIX-*" --sort=-refname | head -n 1)
          if [ -z "$SIGN_ME_BRANCH" ]
          then
            switched="false"
          else
            git checkout --track $SIGN_ME_BRANCH
            switched="true"
          fi
          echo "::set-output name=switched::$switched"

      - name: ⚙ Build metadata-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: ⚙ Update QRs from RPC nodes
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- update --source node

      - name: ⚙ Update QRs from GitHub releases
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- update --source github

      - name: ⚙ Run collector
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- collect

      - name: 📌 Commit changes if PR exists
        if: ${{ steps.checkout-pr.outputs.switched == 'true' }}
        uses: ./.github/workflows/commit-changes
        with:
          message: 'metadata update'

      - name: New PR branch
        if: ${{ steps.checkout-pr.outputs.switched == 'false' }}
        id: new-branch
        run: |
          NAME="$BRANCH_PREFIX-$(date '+%Y-%m-%d')"
          echo "::set-output name=name::$NAME"

      - name: Create Pull Request if not exist
        if: ${{ steps.checkout-pr.outputs.switched == 'false' }}
        id: cpr
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          commit-message: add unsigned QR codes
          branch: ${{ steps.new-branch.outputs.name }}
          delete-branch: true
          base: master
          title: '[Automated] New metadata is available'
          body: |
            In case there are new metadata QRs, run:
            - [ ] `make signer` to sign files
            - [ ] `make cleaner` to remove old QRs
            - [ ] `make collector` to generate new data file for frontend
          draft: true

      - name: Notify Matrix channel
        uses: s3krit/matrix-message-action@v0.0.3
        if: ${{ env.NOTIFY_MATRIX == 'true' && steps.cpr.outputs.pull-request-operation == 'created' }}
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: "# New metadata is available! 📑
[GitHub PR#${{ steps.cpr.outputs.pull-request-number }}](${{ steps.cpr.outputs.pull-request-url }})"
